### PR TITLE
Update vscode-languageclient version

### PR DESCRIPTION
**Pull request by marianaalanis93**
This PR contains (related with #114).

- Update vscode-languageclient version from 7.0.0. to 8.0.0-next.14 (language client newest version).

PR #159 needs to merge this current PR (#162) first to get the complete solution working.

### CODE REVIEW

**Comment by Vtec234** [comment]
It looks like the Windows build is failing, any ideas?

**Review by gebner — APPROVED** [review]
Just waiting for the windows CI fix first.

**Comment by marianaalanis93** [comment]
@lovettchris @gebner @Vtec234 found the issue with the workflow, please check the #163 PR :) thanks! https://github.com/leanprover/vscode-lean4/pull/163

**Comment by marianaalanis93** [comment]
> Just waiting for the windows CI fix first.

Fixed and waiting for review :)

**Review by Vtec234 — APPROVED** [review]

**Pull request merged**
