### PR TITLE
fix: update npm packages

### PR DESCRIPTION
**Pull request by joneugster**
Update `npm` packages to address vulnerabilities.

### CODE REVIEW

**Comment by joneugster** [comment]
see [CI output](https://github.com/leanprover-community/lean4web/actions/runs/6869827016/job/18683421449#step:5:9).

Unfortunately, I didn't learn in #343 how to create the package-lock correctly

**Comment by mhuisi** [comment]
> Apparently there are now more packages after `semver` that need updating, in particular `axios`. See [CI output](https://github.com/leanprover-community/lean4web/actions/runs/6869827016/job/18683421449#step:5:9).
> Unfortunately, I didn't learn in #343 how to create the package-lock correctly

The simplest way: Revert the changes you made to the package-lock, delete the node_module folders in the root directory, lean4-infoview-api, lean4-infoview, and vscode-lean4, and then re-run the setup steps from the docs.

**Comment by joneugster** [comment]
I'm sorry I haven't spotted [the building instructions](https://github.com/leanprover/vscode-lean4/blob/master/docs/dev.md#building) myself, but now I followed them.

(I don't fully understand `learna`, so I deleted all four `package-lock.json` and `node_module/` before following the building instructions: the ones in the main directory and in all three subdirectories. I believe that's right?)

**Comment by mhuisi** [comment]
> I'm sorry I haven't spotted [the building instructions](https://github.com/leanprover/vscode-lean4/blob/master/docs/dev.md#building) myself, but now I followed them.

No worries, it took me a while to figure out myself.

> so I deleted all four package-lock.json and node_module/ before following the building instructions

The `package-lock.json` files shouldn't be deleted - note that they are checked into the repo as well.

Also, I am not sure why this PR deletes the @vscode/vsce dev dependency.

**Comment by joneugster** [comment]
I thought deleting/regenerating the `package-lock.json` was part of properly updating npm dependencies, is it not?

**Comment by mhuisi** [comment]
No. If you want to update dependencies, you should go through `npm` instead (e.g. via `npm outdated` and `npm update`), which manages the lock-file for you. 

Generally speaking, we don't always want to update every dependency to its most recent version. In this PR, we only want to update those with vulnerabilities.

**Comment by joneugster** [comment]
I believe now this looks as it should, and hopefully that means I finally understood all the details.

**Comment by mhuisi** [comment]
Looks correct now!

**Pull request merged**
